# Generated by Django 2.2.3 on 2019-07-31 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_rest', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plan',
            options={'ordering': ('price',)},
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
